name: Publish @guanzhu.me/arco-cli to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Build CLI package
        run: yarn build

      - name: Publish CLI package
        run: npm publish --access public --provenance
